### ISSUE TITLE
Quick Search on top right does not work (white screen)

### ISSUE THREAD

**Issue by shinguz** [aigaion/aigaion#15]
This issue is already reported in issue #14. Which probably should be split up into smaller reports. Here we have at least a bug fix for it:

[Sat Jan 23 10:58:55.847500 2021] [php7:error] [pid 23894] [client 127.0.0.1:57890] PHP Fatal error: Uncaught Error: Call to undefined method CI_DB_mysqli_driver::escape_string() in /home/oli/devel/aigaion2/aigaion/www/application/libraries/search_lib.php:452
Stack trace:
#0 /home/oli/devel/aigaion2/aigaion/www/application/libraries/search_lib.php(177): Search_lib->keywordsToLikeQuery()
#1 /home/oli/devel/aigaion2/aigaion/www/application/libraries/search_lib.php(43): Search_lib->findAuthorsLike()
#2 /home/oli/devel/aigaion2/aigaion/www/application/controllers/search.php(33): Search_lib->simpleSearch()
#3 /home/oli/devel/aigaion2/aigaion/www/system/core/CodeIgniter.php(359): Search->quicksearch()
#4 /home/oli/devel/aigaion2/aigaion/www/index_personal.php(171): require_once('/home/oli/devel...')
#5 {main}
thrown in /home/oli/devel/aigaion2/aigaion/www/application/libraries/search_lib.php on line 452, referer: http://127.0.0.1/aigaion/index.php/topics

diff --git a/www/application/libraries/search_lib.php b/www/application/libraries/search_lib.php
index ad81ff0..9ee5007 100644
--- a/www/application/libraries/search_lib.php
+++ b/www/application/libraries/search_lib.php
@@ -449,7 +449,7 @@ class Search_lib {
//nonexplicit anchoring: match only word beginnings, * for open ends
$prefix_wildcard = '[[:<:]]';
}

     $result .= $fieldname." REGEXP '".$prefix_wildcard.$CI->db->escape_string($keyword)."' ";

     $result .= $fieldname." REGEXP '".$prefix_wildcard.$CI->db->conn_id->escape_string($keyword)."' ";

    }

**Comment by masakik** [comment]
done
