### ISSUE TITLE
Does not proceed installation on Ubuntu and/or AlmaLinux with PHP 8.1

### ISSUE THREAD

**Issue by suobset** [aigaion/aigaion#28]
With downstream RHEL clones going out, and so is CentOS, our org has been refactoring all code to either Debian or AlmaLinux. Initially, we tried refactoring the original Aigaion from our CentOS 7 install, but soon realized that would not work with newer versions of PHP. 

We tried installing the newer version in this repo, and that does not work as well. In both versions, we run into the same error (blank screen after first screen during install). We tried running it on AlmaLinux and Ubuntu, ad run into the same error (MariaDB for AlmaLinux and MySQL for Ubuntu).

Currently, the only install that still works is the original version on the legacy CentOS 7 version. I would have asked this in a forum instead of a GH issue, but it seems this is the only corner of the internet where discussions on this software still take place.

**Comment by suobset** [comment]
Updates: The MySQL part of the install works. However, it is the page where I set the parameters, after which I see a blank blue screen and nothing else.

**Comment by sourcenux** [comment]
Even though it is not a permanent solution: We do have the same problem within our organization with aigaion2 (so the older version). We are currently running it within a docker container, therefore we do not have an outdated host-os, but just a outdated container/app. 

is @masakik still maintaining this project?

**Comment by masakik** [comment]
Hi, Aigaion is a old codeigniter framework application and needs to be upgradede to version 4 to achieve compatibility on new php  and systems.
Unfortunately I have no time to upgrade it on the closest future.

**Comment by suobset** [comment]
No worries. We initially went with the Docker Container method as well, and have since found [Wikindx](https://wikindx.sourceforge.io/web/trunk/index.html) to be a suitable replacement (it works exactly like Aigaion, with a web based interface, modern PHP, and a MySQL/MariaDB database). 

However, it is crucial to note for folks wanting to make a similar switch that the Database for Wikindx is not the same as Aigaion. You will have to manually export from Aigaion, and import into Wikindx. Moreover, Wikindx does not have the feature to auto-populate a website: that needs to be done by exporting a BibTeX from Wikindx and importing into your site. 

However, Wikindx checks virtually every other checkbox that Aigaion does as well. Aigaion can always be used in a Docker Container too :)
